spring:
  profiles:
    active: dev
  cache:
    caffeine:
      spec: maximumSize=2000,expireAfterWrite=60m

logging:
  level:
    ru.yandex.autoschool.weather: DEBUG

management:
  port: 9090
endpoints:
  enabled: false
  env:
    enabled: true
  health:
    enabled: true
  metrics:
    enabled: true

